### PR TITLE
Rename WorkDoneProgress::Done to End

### PR DESCRIPTION
**Pull request by kjeremy**
See: https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workDoneProgressEnd

### CODE REVIEW

**Comment by kjeremy** [comment]
Also removes WorkDoneProgressCancel

**Comment by Marwes** [comment]
Failing on a test on CI otherwise 👍

**Comment by kjeremy** [comment]
Should be good now.

**Comment by Marwes** [comment]
Released as 0.64

**Pull request merged**
