### PR TITLE
Refactor lib.rs roughly by feature

### PR DESCRIPTION
**Pull request by kjeremy**
Maintains existing API compatibility to avoid churn (tested with rust-analyzer).

#175 would have been a lot easier with a refactoring like this. 

@Marwes @matklad I would appreciate feedback on this. lib.rs is still huge.

Towards #80

### CODE REVIEW

**Comment by matklad** [comment]
> I would appreciate feedback on this

FWIW, for that last couple of months I've been thinking about just doing the Microsoft's job here and

* move protocol code from official markdown / language-client-node into a single `protocol.ts` file which:
  * defines the protocol, and only the protocol, as a set  of typescript definitions
  * is easy to sync up with upstream, as you just copy over .ts
* writing a tool (using either swc or tsc) which dumps this .ts into json schema / some other JSON IR which can be used from any language
* writing a generator from that thing into .rs. 

I feel that the protocol is large enough so that maintaining even a single binding by hand is too much work.

**Comment by kjeremy** [comment]
That's essentially microsoft/language-server-protocol/issues/67 Luckily you're on vacation :D

> I feel that the protocol is large enough so that maintaining even a single binding by hand is too much work.

Yes it's **very easy** to miss things.

**Comment by Marwes** [comment]
@matklad Yep, it is really unfortunate that they haven't gotten something like a json schema for it. They actually have that for the debug server protocol which isn't close as important. I were able to generate the bindings for that without to much work so... (https://github.com/Marwes/debugserver-types)

**Comment by kjeremy** [comment]
What do we do about this PR in the meantime?

**Comment by Marwes** [comment]
This is an improvement and doesn't make it more complicated to have it generated at some point so merging! Thanks!

**Pull request merged**
