### PR TITLE
Fix DidSaveTextDocumentParams::text_document to use TextDocumentIdentifier

### PR DESCRIPTION
**Pull request by poliorcetics**
After microsoft/language-server-protocol#1147 and rust-analyzer/rust-analyzer#6603, here is the change this will bring to the spec.

### CODE REVIEW

**Comment by poliorcetics** [comment]
According to recent commits on the lsp spec, it was rolled back to the original, without a version, I'll change it soon

**Comment by kjeremy** [comment]
Thanks! LGTM. 

> it was rolled back to the original, without a version, I'll change it soon

What do you mean by this? Your change matches the fix in the spec: https://github.com/microsoft/language-server-protocol/commit/4bc957323586bf952ee588e8ab2b019fa440e91b

@Marwes Can we get a new version please? Thanks.

**Comment by poliorcetics** [comment]
I did my first commit thinking this would be modified to `OptionalVersionedTextDocumentIdentifier`. It was instead rolled back to `TextDocumentIdentifier`.

**Comment by kjeremy** [comment]
Yes please. Squash and force push. Thanks for tracking this down.

**Comment by poliorcetics** [comment]
Done !

> Thanks for tracking this down.

This is part of the contract of living at `HEAD`. ^^

**Pull request merged**
