### PR TITLE
feat(inlayHint): implement inlayHint

### LINKED ISSUE #230: Implement `inlayHint` Proposed Feature
Hello, I am implementing this feature.  This is simply a tracking issue for the pull request.

Towards https://github.com/denoland/vscode_deno/issues/509

### PR DESCRIPTION
**Pull request by sno2**
See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification

Closes #230

### CODE REVIEW

**Comment by sno2** [comment]
@Marwes Hello, I am fairly sure I have everything covered now in the public API section. Do you know how I would find the data to update the tests?

**Comment by Marwes** [comment]
> @Marwes Hello, I am fairly sure I have everything covered now in the public API section. Do you know how I would find the data to update the tests?

Which tests? For the most part tests are just added when problems are fixed. Before then, testing the types are just as likely to tests wrong behavior as they are to test for the correct behavior as the tests just end up based on whatever the (de)serialization of the types are.

**Review by Marwes — APPROVED** [review]

**Comment by Marwes** [comment]
I don't know how that file was procured either.

**Comment by sno2** [comment]
> I don't know how that file was procured either.

Ok, do you want me to just add a TODO in the test file and we can hopefully add them later once the features are stabilized?  I know there will be implementors coming up so they should be able to catch any possible bugs and these features are under the unstable `proposed` flag.

**Pull request merged**
