### PR TITLE
Redefine textDocument/willSaveWaitUntil as a request

### LINKED ISSUE #142: textDocument/willSaveWaitUntil is a request but implements Notification
According to the LSP specification, it seems like [`textDocument/willSaveWaitUntil`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_willSaveWaitUntil) is supposed to be a client-to-server request that expects a response back. However, it seems like [`WillSaveWaitUntil`](https://docs.rs/lsp-types/0.71.0/lsp_types/notification/enum.WillSaveWaitUntil.html) implements `Notification` instead and doesn't provide a response type. Is this actually correct?

### PR DESCRIPTION
**Pull request by ebkalderon**
### Changed

* Updated the `lsp_notification!()` and `lsp_request!()` macros to match the new status of `WaitSaveWaitUntil`.

### Fixed

* Redefine `textDocument/willSaveWaitUntil` as a request.

Fixes #142.

### CODE REVIEW

**Comment by ebkalderon** [comment]
Ah, looks like there are some compile tests checking the macro that I need to update.

**Comment by ebkalderon** [comment]
Sweet, looks like that fixed it! 🎉

**Comment by ebkalderon** [comment]
Ready for your review when you're ready, @Marwes!

**Comment by Marwes** [comment]
Thanks!

**Comment by Marwes** [comment]
Thanks!

**Pull request merged**
